"""asociar caballos a fechas y categorias

Revision ID: 1703d57471b1
Revises: 916c72fc2f40
Create Date: 2026-08-09 01:24:47.128918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1703d57471b1'
down_revision: Union[str, Sequence[str], None] = '916c72fc2f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caballos_fechas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caballo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caballo_id'], ['caballos.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fecha_id'], ['fechas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caballo_id', 'fecha_id', 'categoria_id', name='uq_caballo_fecha_categoria')
    )
    op.create_index(op.f('ix_caballos_fechas_caballo_id'), 'caballos_fechas', ['caballo_id'], unique=False)
    op.create_index(op.f('ix_caballos_fechas_categoria_id'), 'caballos_fechas', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_caballos_fechas_fecha_id'), 'caballos_fechas', ['fecha_id'], unique=False)
    op.create_index(op.f('ix_caballos_fechas_id'), 'caballos_fechas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caballos_fechas_id'), table_name='caballos_fechas')
    op.drop_index(op.f('ix_caballos_fechas_fecha_id'), table_name='caballos_fechas')
    op.drop_index(op.f('ix_caballos_fechas_categoria_id'), table_name='caballos_fechas')
    op.drop_index(op.f('ix_caballos_fechas_caballo_id'), table_name='caballos_fechas')
    op.drop_table('caballos_fechas')
    # ### end Alembic commands ###
