"""crear tabla campeonatos

Revision ID: 76837901f3d5
Revises: 0a06989fa8c6
Create Date: 2026-07-30 19:38:50.393375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76837901f3d5'
down_revision: Union[str, Sequence[str], None] = '0a06989fa8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campeonatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campeonatos_id'), 'campeonatos', ['id'], unique=False)
    op.create_index(op.f('ix_campeonatos_nombre'), 'campeonatos', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campeonatos_nombre'), table_name='campeonatos')
    op.drop_index(op.f('ix_campeonatos_id'), table_name='campeonatos')
    op.drop_table('campeonatos')
    # ### end Alembic commands ###
