"""crear tabla jinetes

Revision ID: 80a07d64ceb1
Revises: 631a50322068
Create Date: 2026-07-30 22:30:00.193867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a07d64ceb1'
down_revision: Union[str, Sequence[str], None] = '631a50322068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jinetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=30), nullable=True),
    sa.Column('nacionalidad', sa.String(length=60), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('categoria_habitual', sa.String(length=100), nullable=True),
    sa.Column('club_agrupacion', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jinetes_apellidos'), 'jinetes', ['apellidos'], unique=False)
    op.create_index(op.f('ix_jinetes_dni'), 'jinetes', ['dni'], unique=True)
    op.create_index(op.f('ix_jinetes_id'), 'jinetes', ['id'], unique=False)
    op.create_index(op.f('ix_jinetes_localidad'), 'jinetes', ['localidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jinetes_localidad'), table_name='jinetes')
    op.drop_index(op.f('ix_jinetes_id'), table_name='jinetes')
    op.drop_index(op.f('ix_jinetes_dni'), table_name='jinetes')
    op.drop_index(op.f('ix_jinetes_apellidos'), table_name='jinetes')
    op.drop_table('jinetes')
    # ### end Alembic commands ###
