"""crear caballos y tropillas

Revision ID: 916c72fc2f40
Revises: 20fd1174d91e
Create Date: 2026-08-09 01:22:51.480116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916c72fc2f40'
down_revision: Union[str, Sequence[str], None] = '20fd1174d91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tropillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('propietario', sa.String(length=150), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tropillas_id'), 'tropillas', ['id'], unique=False)
    op.create_index(op.f('ix_tropillas_nombre'), 'tropillas', ['nombre'], unique=True)
    op.create_table('caballos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tropilla_id', sa.Integer(), nullable=True),
    sa.Column('pelaje', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tropilla_id'], ['tropillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caballos_id'), 'caballos', ['id'], unique=False)
    op.create_index(op.f('ix_caballos_nombre'), 'caballos', ['nombre'], unique=False)
    op.create_index(op.f('ix_caballos_tropilla_id'), 'caballos', ['tropilla_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caballos_tropilla_id'), table_name='caballos')
    op.drop_index(op.f('ix_caballos_nombre'), table_name='caballos')
    op.drop_index(op.f('ix_caballos_id'), table_name='caballos')
    op.drop_table('caballos')
    op.drop_index(op.f('ix_tropillas_nombre'), table_name='tropillas')
    op.drop_index(op.f('ix_tropillas_id'), table_name='tropillas')
    op.drop_table('tropillas')
    # ### end Alembic commands ###
