"""crear tabla categorias

Revision ID: a3e4866dd6d7
Revises: f4356c40b33c
Create Date: 2026-07-30 21:26:19.786296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e4866dd6d7'
down_revision: Union[str, Sequence[str], None] = 'f4356c40b33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fecha_id'], ['fechas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_fecha_id'), 'categorias', ['fecha_id'], unique=False)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_fecha_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
