"""crear tabla fechas

Revision ID: f4356c40b33c
Revises: 7455f6bada67
Create Date: 2026-07-30 20:37:33.549569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4356c40b33c'
down_revision: Union[str, Sequence[str], None] = '7455f6bada67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campeonato_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('lugar', sa.String(length=150), nullable=True),
    sa.Column('organizador', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campeonato_id'], ['campeonatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fechas_campeonato_id'), 'fechas', ['campeonato_id'], unique=False)
    op.create_index(op.f('ix_fechas_id'), 'fechas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fechas_id'), table_name='fechas')
    op.drop_index(op.f('ix_fechas_campeonato_id'), table_name='fechas')
    op.drop_table('fechas')
    # ### end Alembic commands ###
